services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listing-apartments-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=mongodb://mongo:27017/listingApartmentsDB
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
